### ISSUE TITLE
Unauthorized use of Enigma font software

### ISSUE THREAD

**Issue by JTankard** [mapgears/labs#1]
I notice that you’re using our copyrighted Enigma font software and redistributing them through this repo.

These fonts, whether licensed or not cannot be put them in a public repo. Sorry.

Jeremy Tankard Typography Ltd
www.typography.net

**Comment by adube** [comment]
Understood.  We'll remove them ASAP.  Sorry about that and thanks for reporting this.

**Comment by adube** [comment]
This repository will be deleted.  Thanks again for reporting this.
